INCLUDE(CMakeFindDependencyMacro)
FIND_DEPENDENCY(VLCQtCore)

INCLUDE("${CMAKE_CURRENT_LIST_DIR}/VLCQtQmlTargets.cmake")

SET_TARGET_PROPERTIES(VLCQt::Qml PROPERTIES
    INTERFACE_LINK_LIBRARIES VLCQt::Core
)

IF(NOT STATIC AND ${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    SET(VLCQtQmlFramework ${CMAKE_CURRENT_LIST_DIR}/../../VLCQtQml.framework)
    SET(VLCQtQmlPluginDir ${CMAKE_CURRENT_LIST_DIR}/../../../qml/VLCQt)
ELSE()
    GET_TARGET_PROPERTY(VLCQtQmlLocation VLCQt::Qml INTERFACE_INCLUDE_DIRECTORIES)
    STRING(REGEX REPLACE "/include" "" VLCQtQmlLocation "${VLCQtQmlLocation}")
ENDIF()
